RentWheels/Controllers/CarController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RentWheels.Core.Contracts;
using RentWheels.Core.ViewModels.Car;
using System.Security.Claims;

namespace RentWheels.Controllers
{
	public class CarController : BaseController
	{
		private readonly ICarService carService;
        private readonly IEngineService engineService;
        private readonly ICategoryService categoryService;

        public CarController(
            ICarService _carService,
            IEngineService _engineService,
            ICategoryService _categoryService)
        {
            carService = _carService;
            engineService = _engineService;
            categoryService = _categoryService;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> All([FromQuery] AllCarsQueryViewModel model)
        {
            var cars = await carService.AllAsync(
                model.Category,
                model.Color,
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                model.CarsPerPage);

            model.TotalCarsCount = cars.TotalCarsCount;
            model.Cars = cars.Cars;
            model.TotalPages = cars.TotalPages;
            model.Categories = await categoryService.AllCategoriesNamesAsync();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
		{
            var model = new CarFormViewModel()
            {
                Engines = await engineService.AllEnginesFormAsync(),
                Categories = await categoryService.AllCategoriesFormAsync()
            };

			return View(model);
		}

        [HttpPost]
        public async Task<IActionResult> Add(CarFormViewModel model)
        {
            if (await engineService.EngineExistsAsync(model.EngineId) == false)
            {
                ModelState.AddModelError(nameof(model.EngineId), "Selected engine does not exit!");
            }

			if (await categoryService.CategoryExistsAsync(model.CategoryId) == false)
			{
				ModelState.AddModelError(nameof(model.CategoryId), "Selected category does not exist.");
			}

			if (!ModelState.IsValid)
            {
                model.Engines = await engineService.AllEnginesFormAsync();
                model.Categories = await categoryService.AllCategoriesFormAsync();
                return View(model);
            }

            await carService.CreateAsync(model, User.Id());

			TempData["message"] = "Car successfully added.";
			TempData["messageType"] = "success";

			return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (await carService.CarExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (await carService.HasOwnerWithIdAsync(id, User.Id()) == false && User.IsAdimn() == false)
            {
                return Unauthorized();
            }

            var model = await carService.CreateCarFormViewModelByIdAsync(id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, CarFormViewModel model)
        {
            if (await carService.CarExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (await carService.HasOwnerWithIdAsync(id, User.Id()) == false && User.IsAdimn() == false)
            {
                return Unauthorized();
            }

            if (await engineService.EngineExistsAsync(model.EngineId) == false)
            {
                ModelState.AddModelError(nameof(model.EngineId), "Selected engine does not exist.");              
            }
            
            if (await categoryService.CategoryExistsAsync(model.CategoryId) == false)
            {
                ModelState.AddModelError(nameof(model.CategoryId), "Selected category does not exist.");              
            }

            if (!ModelState.IsValid)
            {
                model.Engines = await engineService.AllEnginesFormAsync();
                model.Categories = await categoryService.AllCategoriesFormAsync();

                return View(model);
            }

            await carService.EditAsync(id, model);

			TempData["message"] = "Car successfully edited.";
			TempData["messageType"] = "success";

			return RedirectToAction(nameof(MyCars));
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if (await carService.CarExistsAsync(id) == false)
            {
                return BadRequest();
            }

            var model = await carService.DetailsAsync(id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Remove(int id)
        {
            if (await carService.CarExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (await carService.HasOwnerWithIdAsync(id, User.Id()) == false && User.IsAdimn() == false)
            {
                return Unauthorized();
            }

            await carService.RemoveCarAsync(id);

            return RedirectToAction(nameof(MyCars));
        }

		[HttpGet]
		public async Task<IActionResult> MyCars()
		{
			var model = await carService.MyCarsAsync(User.Id());

			return View(model);
		}
	}
}

RentWheels/Controllers/MessageController.cs
using Microsoft.AspNetCore.Mvc;
using RentWheels.Core.Contracts;
using RentWheels.Core.ViewModels.Message;
using System.Security.Claims;

namespace RentWheels.Controllers
{
	public class MessageController : BaseController
	{
		private readonly IMessageService messageService;
		private readonly IRentalService rentalService;

        public MessageController(
			IMessageService _messageService,
			IRentalService _rentalService)
        {
            messageService = _messageService;
			rentalService = _rentalService;
        }

		[HttpGet]
		public async Task<IActionResult> MyMessages()
		{
			var model = await messageService.MyMessagesAsync(User.Id());

			return View(model);
		}

        [HttpGet]
		public async Task<IActionResult> SendMessage()
		{
			var model = new MessageFormViewModel();

			model.Rentals = await rentalService.MyRentedCarsForSendingMessageAsync(User.Id());

			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> SendMessage(MessageFormViewModel model)
		{
			if (!ModelState.IsValid)
			{
				model.Rentals = await rentalService.MyRentedCarsForSendingMessageAsync(User.Id());
				return View(model);
			}

			await messageService.SendAsync(model, User.Id());

			TempData["message"] = "Message successfully sent.";
			TempData["messageType"] = "success";

			return RedirectToAction("All", "Car");
		}
	}
}

RentWheels/Controllers/RentalController.cs
using Microsoft.AspNetCore.Mvc;
using RentWheels.Core.Contracts;
using RentWheels.Core.ViewModels.Rental;
using System.Globalization;
using System.Security.Claims;
using static RentWheels.Infrastructure.Constants.DataConstants;

namespace RentWheels.Controllers
{
	public class RentalController : BaseController
	{
		private readonly IRentalService rentalService;
		private readonly ICarService carService;

		public RentalController(
			IRentalService _rentalService,
			ICarService _carService)
		{
			rentalService = _rentalService;
			carService = _carService;

		}

		[HttpGet]
		public async Task<IActionResult> Rent(int id)
		{
			if (await carService.CarExistsAsync(id) == false)
			{
				return BadRequest();
			}

			if (await rentalService.IsCarValidForRentAsync(id, User.Id()) == false)
			{
				return RedirectToAction("All", "Car");
			}

			var model = new RentCarFormViewModel();			

			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> Rent(int id, RentCarFormViewModel model)
		{
			DateTime s = DateTime.Now;
			DateTime e = DateTime.Now;

			if (!DateTime.TryParseExact(model.Start, DateFormated, CultureInfo.InvariantCulture, DateTimeStyles.None
				, out s))
			{
				ModelState.AddModelError(nameof(model.Start), $"Invalid date! Format must be: {DateFormated}");
			}

			if (!DateTime.TryParseExact(model.End, DateFormated, CultureInfo.InvariantCulture, DateTimeStyles.None
				, out e))
			{
				ModelState.AddModelError(nameof(model.End), $"Invalid date! Format must be: {DateFormated}");
			}

			if (s > e)
			{
				ModelState.AddModelError(nameof(model.Start), $"Start date cannot be greater than the end date!");
			}

			if (!ModelState.IsValid)
			{
				return View(model);
			}

			await rentalService.RentCarAsync(model, id, User.Id(), s, e);

			TempData["message"] = "Renting was successful.";
			TempData["messageType"] = "success";

			return RedirectToAction(nameof(MyRented));
		}

		[HttpGet]
		public async Task<IActionResult> MyRented()
		{
			var cars = await rentalService.MyRentedCarsAsync(User.Id());

			return View(cars);
		}

		[HttpPost]
		public async Task<IActionResult> End(int id)
		{
			if (await rentalService.RentalExistsAsync(id) == false)
			{
				return BadRequest();
			}

			if (await rentalService.HasRenterWithIdAsync(id, User.Id()) == false && User.IsAdimn() == false)
			{
				return Unauthorized();
			}

			await rentalService.EndRentAsync(id);

			TempData["message"] = "Your rental was ended.";
			TempData["messageType"] = "success";

			return RedirectToAction(nameof(MyRented));
		}

		[HttpGet]
		public async Task<IActionResult> Edit(int id)
		{
			if (await rentalService.RentalExistsAsync(id) == false)
			{
				return BadRequest();
			}

			if (await rentalService.HasRenterWithIdAsync(id, User.Id()) == false && User.IsAdimn() == false)
			{
				return Unauthorized();
			}

			var model = await rentalService.CreateRentalFormViewModelByIdAsync(id);

			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> Edit(int id, RentCarFormViewModel model)
		{
			if (await rentalService.RentalExistsAsync(id) == false)
			{
				return BadRequest();
			}

			if (await rentalService.HasRenterWithIdAsync(id, User.Id()) == false && User.IsAdimn() == false)
			{
				return Unauthorized();
			}

			DateTime s = DateTime.Now;
			DateTime e = DateTime.Now;

			if (!DateTime.TryParseExact(model.Start, DateFormated, CultureInfo.InvariantCulture, DateTimeStyles.None
				, out s))
			{
				ModelState.AddModelError(nameof(model.Start), $"Invalid date! Format must be: {DateFormated}");
			}

			if (!DateTime.TryParseExact(model.End, DateFormated, CultureInfo.InvariantCulture, DateTimeStyles.None
				, out e))
			{
				ModelState.AddModelError(nameof(model.End), $"Invalid date! Format must be: {DateFormated}");
			}

			if (s > e)
			{
				ModelState.AddModelError(nameof(model.Start), $"Start date cannot be greater than the end date!");
			}

			if (!ModelState.IsValid)
			{
				return View(model);
			}

			await rentalService.EditAsync(id, model, s, e);

			TempData["message"] = "Rental successfully edited.";
			TempData["messageType"] = "success";

			return RedirectToAction(nameof(MyRented));
		}

		[HttpGet]
		public async Task<IActionResult> MyRentHistory()
		{
			var cars = await rentalService.MyRentHistoryAsync(User.Id());

			return View(cars);
		}
	}
}

RentWheels/Views/Shared/_CarFormPartial.cshtml
@model CarFormViewModel

<form method="post">
	<div class="mb-3">
		<label asp-for="@Model.Brand" class="form-label">Brand</label>
		<input asp-for="@Model.Brand" class="form-control" required />
		<span asp-validation-for="@Model.Brand" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label asp-for="@Model.CarModel" class="form-label">Model</label>
		<input asp-for="@Model.CarModel" class="form-control" required />
		<span asp-validation-for="@Model.CarModel" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label asp-for="@Model.Color" class="form-label">Color</label>
		<input asp-for="@Model.Color" class="form-control" required />
		<span asp-validation-for="@Model.Color" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label asp-for="@Model.Year" class="form-label">Year</label>
		<input asp-for="@Model.Year" class="form-control" required placeholder="Enter year" />
		<span asp-validation-for="@Model.Year" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label asp-for="@Model.ImageUrl" class="form-label">Image URL</label>
		<input asp-for="@Model.ImageUrl" class="form-control" required />
		<span asp-validation-for="@Model.ImageUrl" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label asp-for="@Model.PricePerDay" class="form-label">Price Per Day</label>
		<input asp-for="@Model.PricePerDay" class="form-control" required placeholder="Enter price" />
		<span asp-validation-for="@Model.PricePerDay" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label asp-for="@Model.EngineId" class="form-label">Engine</label>
		<select asp-for="@Model.EngineId" class="form-control" required">
			@foreach (var engine in Model.Engines)
			{
				<option value="@engine.Id">@engine.Name</option>
			}
		</select>
		<span asp-validation-for="@Model.EngineId" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label asp-for="@Model.CategoryId" class="form-label">Category</label>
		<select asp-for="@Model.CategoryId" class="form-control" required">
			@foreach (var category in Model.Categories)
			{
				<option value="@category.Id">@category.Name</option>
			}
		</select>
		<span asp-validation-for="@Model.CategoryId" class="text-danger"></span>
	</div>

	<button type="submit" class="btn btn-success">Finish</button>
</form>

RentWheels/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]RentWheels</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RentWheels.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body style="background-image: url('/images/background.jpg'); background-size: cover;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RentWheels</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">                       
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Car" asp-action="All">All Cars</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Car" asp-action="Add">Add A Car</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Rental" asp-action="MyRented">My Active Rents</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Message" asp-action="SendMessage">Report Problem</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-light bg-dark">
        <div class="col-lg-0">
            &copy; @DateTime.Now.Year - RentWheels
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RentWheels/Views/Shared/_Notification.cshtml
@if (TempData["message"] != null && TempData["messageType"] != null)
{
	<script src="/lib/jquery/dist/jquery.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.@(TempData["messageType"])('@TempData["message"]');
	</script>
}

RentWheels/Views/Shared/_RentalFormPartial.cshtml
@model RentCarFormViewModel

<form method="post">
	<div class="mb-3">
		<label asp-for="@Model.PickUp" class="form-label">Pick Up Location</label>
		<select asp-for="@Model.PickUp" class="form-control" required">
			@foreach (var city in Model.Cities)
			{
				<option value="@city">@city</option>
			}
		</select>
		<span asp-validation-for="@Model.PickUp" class="text-danger"></span>	
	</div>

	<div class="mb-3">
		<label asp-for="@Model.DropOff" class="form-label">Drop Off Location</label>
		<select asp-for="@Model.DropOff" class="form-control" required">
			@foreach (var city in Model.Cities)
			{
				<option value="@city">@city</option>
			}
		</select>
		<span asp-validation-for="@Model.DropOff" class="text-danger"></span>	
	</div>

	<div class="mb-3">
		<label asp-for="@Model.Start" class="form-label">Start Date</label>
		<input asp-for="@Model.Start" class="form-control" required" placeholder="dd/mm/yyyy" />
		<span asp-validation-for="@Model.Start" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label asp-for="@Model.End" class="form-label">End Date</label>
		<input asp-for="@Model.End" class="form-control" required" placeholder="dd/mm/yyyy" />
		<span asp-validation-for="@Model.End" class="text-danger"></span>
	</div>

	<button type="submit" class="btn btn-success">Finish</button>
</form>

RentWheels/Views/Shared/_ReviewFormPartial.cshtml
@model ReviewFormViewModel

<form method="post">
	<div class="mb-3">
		<label asp-for="@Model.Rating" class="form-label">Rating</label>
		<input asp-for="@Model.Rating" class="form-control" required />
		<span asp-validation-for="@Model.Rating" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label asp-for="@Model.Comment" class="form-label">Comment</label>
		<input asp-for="@Model.Comment" class="form-control" required />
		<span asp-validation-for="@Model.Comment" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<input type="hidden" asp-for="@Model.CarId" />
	</div>

	<button type="submit" class="btn btn-success">Finish</button>
</form>