RentWheels/Areas/Admin/Controllers/AdminCarController.cs
using Microsoft.AspNetCore.Mvc;
using RentWheels.Core.Contracts;
using RentWheels.Core.Services;
using RentWheels.Core.ViewModels.Car;
using System.Security.Claims;

namespace RentWheels.Areas.Admin.Controllers
{
	public class AdminCarController : BaseAdminController
	{
		private readonly ICarService carService;
		private readonly IEngineService engineService;
		private readonly ICategoryService categoryService;

        public AdminCarController(
			ICarService _carService,
			IEngineService _engineService,
			ICategoryService _categoryService)
        {
            carService = _carService;
			engineService = _engineService;
			categoryService = _categoryService;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var model = await carService.AllCarsAsync();

            return View(model);
        }

		[HttpGet]
		public async Task<IActionResult> Edit(int id)
		{
			if (await carService.CarExistsAsync(id) == false)
			{
				return BadRequest();
			}

			if (await carService.HasOwnerWithIdAsync(id, User.Id()) == false && User.IsAdimn() == false)
			{
				return Unauthorized();
			}

			var model = await carService.CreateCarFormViewModelByIdAsync(id);

			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> Edit(int id, CarFormViewModel model)
		{
			if (await carService.CarExistsAsync(id) == false)
			{
				return BadRequest();
			}

			if (await carService.HasOwnerWithIdAsync(id, User.Id()) == false && User.IsAdimn() == false)
			{
				return Unauthorized();
			}

			if (await engineService.EngineExistsAsync(model.EngineId) == false)
			{
				ModelState.AddModelError(nameof(model.EngineId), "Selected engine does not exist.");
			}

			if (await categoryService.CategoryExistsAsync(model.CategoryId) == false)
			{
				ModelState.AddModelError(nameof(model.CategoryId), "Selected category does not exist.");
			}

			if (!ModelState.IsValid)
			{
				model.Engines = await engineService.AllEnginesFormAsync();
				model.Categories = await categoryService.AllCategoriesFormAsync();

				return View(model);
			}

			await carService.EditAsync(id, model);

			return RedirectToAction(nameof(All));
		}

		[HttpPost]
		public async Task<IActionResult> Remove(int id)
		{
			if (await carService.CarExistsAsync(id) == false)
			{
				return BadRequest();
			}

			if (await carService.HasOwnerWithIdAsync(id, User.Id()) == false && User.IsAdimn() == false)
			{
				return Unauthorized();
			}

			await carService.RemoveCarAsync(id);

			return RedirectToAction(nameof(All));
		}
	}
}

RentWheels/Areas/Admin/Controllers/AdminRentalController.cs
using Microsoft.AspNetCore.Mvc;
using RentWheels.Core.Contracts;
using RentWheels.Core.ViewModels.Rental;
using System.Globalization;
using System.Security.Claims;
using static RentWheels.Infrastructure.Constants.DataConstants;

namespace RentWheels.Areas.Admin.Controllers
{
    public class AdminRentalController : BaseAdminController
	{
		private readonly IRentalService rentalService;

        public AdminRentalController(IRentalService _rentalService)
        {
			rentalService = _rentalService;
        }

        [HttpGet]
		public async Task<IActionResult> All()
		{
			var model = await rentalService.AllActiveRentalsAsync();

			return View(model);
		}

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (await rentalService.RentalExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (await rentalService.HasRenterWithIdAsync(id, User.Id()) == false && User.IsAdimn() == false)
            {
                return Unauthorized();
            }

            var model = await rentalService.CreateRentalFormViewModelByIdAsync(id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, RentCarFormViewModel model)
        {
            if (await rentalService.RentalExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (await rentalService.HasRenterWithIdAsync(id, User.Id()) == false && User.IsAdimn() == false)
            {
                return Unauthorized();
            }

            DateTime s = DateTime.Now;
            DateTime e = DateTime.Now;

            if (!DateTime.TryParseExact(model.Start, DateFormated, CultureInfo.InvariantCulture, DateTimeStyles.None
                , out s))
            {
                ModelState.AddModelError(nameof(model.Start), $"Invalid date! Format must be: {DateFormated}");
            }

            if (!DateTime.TryParseExact(model.End, DateFormated, CultureInfo.InvariantCulture, DateTimeStyles.None
                , out e))
            {
                ModelState.AddModelError(nameof(model.End), $"Invalid date! Format must be: {DateFormated}");
            }

            if (s > e)
            {
                ModelState.AddModelError(nameof(model.Start), $"Start date cannot be greater than the end date!");
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await rentalService.EditAsync(id, model, s, e);

            return RedirectToAction(nameof(All));
        }

        [HttpPost]
        public async Task<IActionResult> End(int id)
        {
            if (await rentalService.RentalExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (await rentalService.HasRenterWithIdAsync(id, User.Id()) == false && User.IsAdimn() == false)
            {
                return Unauthorized();
            }

            await rentalService.EndRentAsync(id);

            return RedirectToAction(nameof(All));
        }
    }
}

RentWheels/Areas/Admin/Controllers/AdminReviewController.cs
using Microsoft.AspNetCore.Mvc;
using RentWheels.Core.Contracts;
using RentWheels.Core.ViewModels.Review;
using System.Security.Claims;

namespace RentWheels.Areas.Admin.Controllers
{
    public class AdminReviewController : BaseAdminController
    {
        private readonly IReviewService reviewService;
        private readonly ICarService carService;

        public AdminReviewController(
            IReviewService _reviewService,
            ICarService _carService)
        {
            reviewService = _reviewService;
            carService = _carService;
        }

		[HttpGet]
		public async Task<IActionResult> AllByCar(int id)
		{
			if (await carService.CarExistsAsync(id) == false)
			{
				return BadRequest();
			}

			var model = await reviewService.GetForCarAsync(id);

			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> Remove(int id)
		{
			if (await reviewService.ReviewExistsAsync(id) == false)
			{
				return BadRequest();
			}

			if (await reviewService.HasReviewerWithIdAsync(id, User.Id()) == false && User.IsAdimn() == false)
			{
				return Unauthorized();
			}

			int carId = await reviewService.GetReviewCarIdAsync(id);

			await reviewService.RemoveReviewAsync(id);

			return RedirectToAction(nameof(AllByCar), new { id = carId });
		}

		[HttpGet]
		public async Task<IActionResult> Edit(int id)
		{
			if (await reviewService.ReviewExistsAsync(id) == false)
			{
				return BadRequest();
			}

			if (await reviewService.HasReviewerWithIdAsync(id, User.Id()) == false && User.IsAdimn() == false)
			{
				return Unauthorized();
			}

			var model = await reviewService.CreateReviewFormViewModelByIdAsync(id);

			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> Edit(int id, ReviewFormViewModel model)
		{
			if (await reviewService.ReviewExistsAsync(id) == false)
			{
				return BadRequest();
			}

			if (await reviewService.HasReviewerWithIdAsync(id, User.Id()) == false && User.IsAdimn() == false)
			{
				return Unauthorized();
			}

			await reviewService.EditAsync(id, model);

			return RedirectToAction(nameof(AllByCar), new { id = model.CarId });
		}
	}
}

RentWheels/Areas/Admin/Views/Shared/_AdminCarFormPartial.cshtml
@model CarFormViewModel

<form asp-action="Edit" asp-controller="AdminCar" asp-area="Admin" method="post">
	<div class="mb-3">
		<label asp-for="@Model.Brand" class="form-label">Brand</label>
		<input asp-for="@Model.Brand" class="form-control" required />
		<span asp-validation-for="@Model.Brand" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label asp-for="@Model.CarModel" class="form-label">Model</label>
		<input asp-for="@Model.CarModel" class="form-control" required />
		<span asp-validation-for="@Model.CarModel" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label asp-for="@Model.Color" class="form-label">Color</label>
		<input asp-for="@Model.Color" class="form-control" required />
		<span asp-validation-for="@Model.Color" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label asp-for="@Model.Year" class="form-label">Year</label>
		<input asp-for="@Model.Year" class="form-control" required placeholder="Enter year" />
		<span asp-validation-for="@Model.Year" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label asp-for="@Model.ImageUrl" class="form-label">Image URL</label>
		<input asp-for="@Model.ImageUrl" class="form-control" required />
		<span asp-validation-for="@Model.ImageUrl" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label asp-for="@Model.PricePerDay" class="form-label">Price Per Day</label>
		<input asp-for="@Model.PricePerDay" class="form-control" required placeholder="Enter price" />
		<span asp-validation-for="@Model.PricePerDay" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label asp-for="@Model.EngineId" class="form-label">Engine</label>
		<select asp-for="@Model.EngineId" class="form-control" required">
			@foreach (var engine in Model.Engines)
			{
				<option value="@engine.Id">@engine.Name</option>
			}
		</select>
		<span asp-validation-for="@Model.EngineId" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label asp-for="@Model.CategoryId" class="form-label">Category</label>
		<select asp-for="@Model.CategoryId" class="form-control" required">
			@foreach (var category in Model.Categories)
			{
				<option value="@category.Id">@category.Name</option>
			}
		</select>
		<span asp-validation-for="@Model.CategoryId" class="text-danger"></span>
	</div>

	<button type="submit" class="btn btn-success">Finish</button>
</form>

RentWheels/Areas/Admin/Views/Shared/_AdminPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<ul class="navbar-nav">
	@if (SignInManager.IsSignedIn(User))
	{
		<li class="nav-item">
			<a class="nav-link text-light" asp-area="" asp-action="Index" asp-controller="Home">Go to RentWheels</a>
		</li>
		<li class="nav-item">
			<a class="nav-link text-light">Hello @User.Identity?.Name!</a>
		</li>
		<li class="nav-item">
			<form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
				<button type="submit" class="nav-link btn btn-link text-light">Logout</button>
			</form>
		</li>
	}
</ul>

RentWheels/Areas/Admin/Views/Shared/_AdminRentalFormPartial.cshtml
@model RentCarFormViewModel

<form method="post">
	<div class="mb-3">
		<label asp-for="@Model.PickUp" class="form-label">Pick Up Location</label>
		<select asp-for="@Model.PickUp" class="form-control" required">
			@foreach (var city in Model.Cities)
			{
				<option value="@city">@city</option>
			}
		</select>
		<span asp-validation-for="@Model.PickUp" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label asp-for="@Model.DropOff" class="form-label">Drop Off Location</label>
		<select asp-for="@Model.DropOff" class="form-control" required">
			@foreach (var city in Model.Cities)
			{
				<option value="@city">@city</option>
			}
		</select>
		<span asp-validation-for="@Model.DropOff" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label asp-for="@Model.Start" class="form-label">Start Date</label>
		<input asp-for="@Model.Start" class="form-control" required" />
		<span asp-validation-for="@Model.Start" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label asp-for="@Model.End" class="form-label">End Date</label>
		<input asp-for="@Model.End" class="form-control" required" />
		<span asp-validation-for="@Model.End" class="text-danger"></span>
	</div>

	<button type="submit" class="btn btn-success">Finish</button>
</form>

RentWheels/Areas/Admin/Views/Shared/_AdminReviewFormPartial.cshtml
@model ReviewFormViewModel

<form asp-action="Edit" asp-controller="AdminReview" asp-area="Admin" method="post">
	<div class="mb-3">
		<label asp-for="@Model.Rating" class="form-label">Rating</label>
		<input asp-for="@Model.Rating" class="form-control" required />
		<span asp-validation-for="@Model.Rating" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label asp-for="@Model.Comment" class="form-label">Comment</label>
		<input asp-for="@Model.Comment" class="form-control" required />
		<span asp-validation-for="@Model.Comment" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<input type="hidden" asp-for="@Model.CarId" />
	</div>

	<button type="submit" class="btn btn-success">Finish</button>
</form>

RentWheels/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]RentWheels - Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RentWheels.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RentWheels</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">                       
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="Admin" asp-controller="AdminCar" asp-action="All">Manage Cars</a>                        
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="Admin" asp-controller="AdminRental" asp-action="All">Manage Rentals</a>
                        </li>
                    </ul>
                    <partial name="_AdminPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-light bg-dark">
        <div class="col-lg-0">
            &copy; @DateTime.Now.Year - RentWheels
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>