RentWheels/Controllers/CarController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RentWheels.Core.Contracts;
using RentWheels.Core.ViewModels.Car;
using System.Security.Claims;

namespace RentWheels.Controllers
{
	public class CarController : BaseController
	{
		private readonly ICarService carService;
        private readonly IEngineService engineService;
        private readonly ICategoryService categoryService;

        public CarController(
            ICarService _carService,
            IEngineService _engineService,
            ICategoryService _categoryService)
        {
            carService = _carService;
            engineService = _engineService;
            categoryService = _categoryService;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> All([FromQuery] AllCarsQueryViewModel model)
        {
            var cars = await carService.AllAsync(
                model.Category,
                model.Color,
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                model.CarsPerPage);

            model.TotalCarsCount = cars.TotalCarsCount;
            model.Cars = cars.Cars;
            model.TotalPages = cars.TotalPages;
            model.Categories = await categoryService.AllCategoriesNamesAsync();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
		{
            var model = new CarFormViewModel()
            {
                Engines = await engineService.AllEnginesFormAsync(),
                Categories = await categoryService.AllCategoriesFormAsync()
            };

			return View(model);
		}

        [HttpPost]
        public async Task<IActionResult> Add(CarFormViewModel model)
        {
            if (await engineService.EngineExistsAsync(model.EngineId) == false)
            {
                ModelState.AddModelError(nameof(model.EngineId), "Selected engine does not exit!");
            }

			if (await categoryService.CategoryExistsAsync(model.CategoryId) == false)
			{
				ModelState.AddModelError(nameof(model.CategoryId), "Selected category does not exist.");
			}

			if (!ModelState.IsValid)
            {
                model.Engines = await engineService.AllEnginesFormAsync();
                model.Categories = await categoryService.AllCategoriesFormAsync();
                return View(model);
            }

            await carService.CreateAsync(model, User.Id());

			TempData["message"] = "Car successfully added.";
			TempData["messageType"] = "success";

			return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (await carService.CarExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (await carService.HasOwnerWithIdAsync(id, User.Id()) == false && User.IsAdimn() == false)
            {
                return Unauthorized();
            }

            var model = await carService.CreateCarFormViewModelByIdAsync(id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, CarFormViewModel model)
        {
            if (await carService.CarExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (await carService.HasOwnerWithIdAsync(id, User.Id()) == false && User.IsAdimn() == false)
            {
                return Unauthorized();
            }

            if (await engineService.EngineExistsAsync(model.EngineId) == false)
            {
                ModelState.AddModelError(nameof(model.EngineId), "Selected engine does not exist.");              
            }
            
            if (await categoryService.CategoryExistsAsync(model.CategoryId) == false)
            {
                ModelState.AddModelError(nameof(model.CategoryId), "Selected category does not exist.");              
            }

            if (!ModelState.IsValid)
            {
                model.Engines = await engineService.AllEnginesFormAsync();
                model.Categories = await categoryService.AllCategoriesFormAsync();

                return View(model);
            }

            await carService.EditAsync(id, model);

			TempData["message"] = "Car successfully edited.";
			TempData["messageType"] = "success";

			return RedirectToAction(nameof(MyCars));
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if (await carService.CarExistsAsync(id) == false)
            {
                return BadRequest();
            }

            var model = await carService.DetailsAsync(id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Remove(int id)
        {
            if (await carService.CarExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (await carService.HasOwnerWithIdAsync(id, User.Id()) == false && User.IsAdimn() == false)
            {
                return Unauthorized();
            }

            await carService.RemoveCarAsync(id);

            return RedirectToAction(nameof(MyCars));
        }

		[HttpGet]
		public async Task<IActionResult> MyCars()
		{
			var model = await carService.MyCarsAsync(User.Id());

			return View(model);
		}
	}
}

RentWheels/Controllers/EngineController.cs
using Microsoft.AspNetCore.Mvc;
using RentWheels.Core.Contracts;

namespace RentWheels.Controllers
{
    public class EngineController : BaseController
    {
        private readonly IEngineService engineService;

        public EngineController(IEngineService _engineService)
        {
            engineService = _engineService;
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if (await engineService.EngineExistsAsync(id) == false)
            {
                return BadRequest();
            }

            var model = await engineService.DetailsAsync(id);

            return View(model);
        }
    }
}

RentWheels/Controllers/RentalController.cs
using Microsoft.AspNetCore.Mvc;
using RentWheels.Core.Contracts;
using RentWheels.Core.ViewModels.Rental;
using System.Globalization;
using System.Security.Claims;
using static RentWheels.Infrastructure.Constants.DataConstants;

namespace RentWheels.Controllers
{
	public class RentalController : BaseController
	{
		private readonly IRentalService rentalService;
		private readonly ICarService carService;

		public RentalController(
			IRentalService _rentalService,
			ICarService _carService)
		{
			rentalService = _rentalService;
			carService = _carService;

		}

		[HttpGet]
		public async Task<IActionResult> Rent(int id)
		{
			if (await carService.CarExistsAsync(id) == false)
			{
				return BadRequest();
			}

			if (await rentalService.IsCarValidForRentAsync(id, User.Id()) == false)
			{
				return RedirectToAction("All", "Car");
			}

			var model = new RentCarFormViewModel();			

			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> Rent(int id, RentCarFormViewModel model)
		{
			DateTime s = DateTime.Now;
			DateTime e = DateTime.Now;

			if (!DateTime.TryParseExact(model.Start, DateFormated, CultureInfo.InvariantCulture, DateTimeStyles.None
				, out s))
			{
				ModelState.AddModelError(nameof(model.Start), $"Invalid date! Format must be: {DateFormated}");
			}

			if (!DateTime.TryParseExact(model.End, DateFormated, CultureInfo.InvariantCulture, DateTimeStyles.None
				, out e))
			{
				ModelState.AddModelError(nameof(model.End), $"Invalid date! Format must be: {DateFormated}");
			}

			if (s > e)
			{
				ModelState.AddModelError(nameof(model.Start), $"Start date cannot be greater than the end date!");
			}

			if (!ModelState.IsValid)
			{
				return View(model);
			}

			await rentalService.RentCarAsync(model, id, User.Id(), s, e);

			TempData["message"] = "Renting was successful.";
			TempData["messageType"] = "success";

			return RedirectToAction(nameof(MyRented));
		}

		[HttpGet]
		public async Task<IActionResult> MyRented()
		{
			var cars = await rentalService.MyRentedCarsAsync(User.Id());

			return View(cars);
		}

		[HttpPost]
		public async Task<IActionResult> End(int id)
		{
			if (await rentalService.RentalExistsAsync(id) == false)
			{
				return BadRequest();
			}

			if (await rentalService.HasRenterWithIdAsync(id, User.Id()) == false && User.IsAdimn() == false)
			{
				return Unauthorized();
			}

			await rentalService.EndRentAsync(id);

			TempData["message"] = "Your rental was ended.";
			TempData["messageType"] = "success";

			return RedirectToAction(nameof(MyRented));
		}

		[HttpGet]
		public async Task<IActionResult> Edit(int id)
		{
			if (await rentalService.RentalExistsAsync(id) == false)
			{
				return BadRequest();
			}

			if (await rentalService.HasRenterWithIdAsync(id, User.Id()) == false && User.IsAdimn() == false)
			{
				return Unauthorized();
			}

			var model = await rentalService.CreateRentalFormViewModelByIdAsync(id);

			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> Edit(int id, RentCarFormViewModel model)
		{
			if (await rentalService.RentalExistsAsync(id) == false)
			{
				return BadRequest();
			}

			if (await rentalService.HasRenterWithIdAsync(id, User.Id()) == false && User.IsAdimn() == false)
			{
				return Unauthorized();
			}

			DateTime s = DateTime.Now;
			DateTime e = DateTime.Now;

			if (!DateTime.TryParseExact(model.Start, DateFormated, CultureInfo.InvariantCulture, DateTimeStyles.None
				, out s))
			{
				ModelState.AddModelError(nameof(model.Start), $"Invalid date! Format must be: {DateFormated}");
			}

			if (!DateTime.TryParseExact(model.End, DateFormated, CultureInfo.InvariantCulture, DateTimeStyles.None
				, out e))
			{
				ModelState.AddModelError(nameof(model.End), $"Invalid date! Format must be: {DateFormated}");
			}

			if (s > e)
			{
				ModelState.AddModelError(nameof(model.Start), $"Start date cannot be greater than the end date!");
			}

			if (!ModelState.IsValid)
			{
				return View(model);
			}

			await rentalService.EditAsync(id, model, s, e);

			TempData["message"] = "Rental successfully edited.";
			TempData["messageType"] = "success";

			return RedirectToAction(nameof(MyRented));
		}

		[HttpGet]
		public async Task<IActionResult> MyRentHistory()
		{
			var cars = await rentalService.MyRentHistoryAsync(User.Id());

			return View(cars);
		}
	}
}

RentWheels/Controllers/ReviewController.cs
using Microsoft.AspNetCore.Mvc;
using RentWheels.Core.Contracts;
using RentWheels.Core.ViewModels.Review;
using System.Security.Claims;

namespace RentWheels.Controllers
{
	public class ReviewController : BaseController
	{
		private readonly IReviewService reviewService;
		private readonly ICarService carService;

        public ReviewController(
			IReviewService _reviewService,
			ICarService _carService)
        {
			reviewService = _reviewService;
			carService = _carService;
		}

        [HttpGet]
		public async Task<IActionResult> AllByCar(int id)
		{
			if (await carService.CarExistsAsync(id) == false)
			{
				return BadRequest();
			}

			var model = await reviewService.GetForCarAsync(id);

			ViewData["carId"] = id;

			return View(model);
		}

		[HttpGet]
		public async Task<IActionResult> Add(int id)
		{
			if (await carService.HasOwnerWithIdAsync(id, User.Id()) == true)
			{
				return RedirectToAction(nameof(AllByCar), new { id = id});
			}

			var model = new ReviewFormViewModel()
			{
				CarId = id
			};

			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> Add(ReviewFormViewModel model)
		{
			if (await carService.HasOwnerWithIdAsync(model.CarId, User.Id()) == true)
			{
				return RedirectToAction(nameof(AllByCar), new { id = model.CarId });
			}

			if (!ModelState.IsValid)
			{
				return View(model);
			}

			await reviewService.AddAsync(model, User.Id());

            TempData["message"] = "Review successfully added.";
            TempData["messageType"] = "success";

            return RedirectToAction(nameof(AllByCar), new { id = model.CarId});
		}

		[HttpPost]
		public async Task<IActionResult> Remove(int id)
		{
			if (await reviewService.ReviewExistsAsync(id) == false)
			{
				return BadRequest();
			}

			if (await reviewService.HasReviewerWithIdAsync(id, User.Id()) == false && User.IsAdimn() == false)
			{
				return Unauthorized();
			}

			int carId = await reviewService.GetReviewCarIdAsync(id);

			await reviewService.RemoveReviewAsync(id);

			TempData["message"] = "Review successfully removed.";
			TempData["messageType"] = "success";

			return RedirectToAction(nameof(AllByCar), new { id = carId });
		}

		[HttpGet]
		public async Task<IActionResult> Edit(int id)
		{
			if (await reviewService.ReviewExistsAsync(id) == false)
			{
				return BadRequest();
			}

			if (await reviewService.HasReviewerWithIdAsync(id, User.Id()) == false && User.IsAdimn() == false)
			{
				return Unauthorized();
			}

			var model = await reviewService.CreateReviewFormViewModelByIdAsync(id);

			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> Edit(int id, ReviewFormViewModel model)
		{
			if (await reviewService.ReviewExistsAsync(id) == false)
			{
				return BadRequest();
			}

			if (await reviewService.HasReviewerWithIdAsync(id, User.Id()) == false && User.IsAdimn() == false)
			{
				return Unauthorized();
			}

			await reviewService.EditAsync(id, model);

			TempData["message"] = "Review successfully edited.";
			TempData["messageType"] = "success";

			return RedirectToAction(nameof(AllByCar), new { id = model.CarId });
		}
	}
}

RentWheels/Views/Car/Add.cshtml
@model CarFormViewModel

<h2 class="text-center">List your car for renting</h2>

<partial name="_CarFormPartial" model="@Model"/>

@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

RentWheels/Views/Car/All.cshtml
@using System.Security.Claims
@model AllCarsQueryViewModel

<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>Entities</title>
	<style>
		.entity-card {
			margin-bottom: 20px;
			width: 400px;
		}

			.entity-card img {
				max-width: 100%;
				height: auto;
			}
	</style>
</head>
<body>
	<partial name="_Notification"/>

	<form method="get">
		<div class="row">
			<div class="form-group col-md-1 d-flex justify-content-between">
				<div class="form-group">
					<label asp-for="Category"></label>
					<select asp-for="Category" class="form-control">
						<option value="">All</option>
						@foreach (var category in Model.Categories)
						{
							<option value="@category">@category</option>
						}
					</select>
				</div>
			</div>

			<div class="form-group col-md-2">
				<label asp-for="Color"></label>
				<input asp-for="Color" class="form-control">
			</div>

			<div class="form-group col-md-3">
				<label asp-for="SearchTerm"></label>
				<input asp-for="SearchTerm" class="form-control">
			</div>

			<div class="form-group col-md-3">
				<div class="form-group">
					<label asp-for="Sorting"></label>
					<select asp-for="Sorting" class="form-control">
						<option value="0">Newest offers</option>
						<option value="1">Year Descending</option>
						<option value="2">Price Ascending</option>
						<option value="3">Price Descending</option>
					</select>
				</div>
			</div>

			<div class="col-md-3">
				<div class="form-group mt-3 p-2">
					<input type="submit" value="Search" class="btn btn-primary" />
				</div>
			</div>
		</div>
	</form>
	<div class="container">
		<div class="row">
			@foreach (var car in Model.Cars)
			{
				<div class="col-md-6">
					<div class="card entity-card">
						<img class="card-img-top" src="@car.ImageUrl" alt="Entity Image">
						<div class="card-body">
							<h5 class="card-title">@car.Brand</h5>
							<p class="card-text">Model: @car.CarModel</p>
							<p class="card-text">Year: @car.Year</p>
							<div class="d-flex justify-content-between">
								<a asp-action="Details" asp-controller="Car" asp-route-id="@car.Id" class="btn btn-primary">Details</a>
								<a asp-action="AllByCar" asp-controller="Review" asp-route-id="@car.Id" class="btn btn-secondary">Reviews</a>
								@if (car.OwnerId != User.Id())
								{
									<a asp-action="Rent" asp-controller="Rental" asp-route-id="@car.Id" class="btn btn-success">Rent</a>
								}
								else
								{
									<btn class ="btn btn-success disabled">Rent</btn>
								}
							</div>
						</div>
					</div>
				</div>
			}
		</div>
		<nav aria-label="Entities Pagination">
			<ul class="pagination justify-content-center">
				@for (int i = 1; i <= Model.TotalPages; i++)
				{
					<li class="page-item @(i == Model.CurrentPage ? "active" : "")">
						<a class="page-link" href="?currentpage=@i&category=@Model.Category&color=@Model.Color&searchTerm=@Model.SearchTerm&sorting=@Model.Sorting">@i</a>
					</li>
				}
			</ul>
		</nav>
	</div>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

RentWheels/Views/Car/Details.cshtml
@model CarDetailsViewModel

<!DOCTYPE html>
<html>
<head>
	<title>Car Details</title>
</head>
<body>
	<div class="container mt-5">
		<h1 class="text-center">@($"{Model.Brand} {Model.CarModel}")</h1>
		<div class="card mt-3">
			<div class="row no-gutters">
				<div class="col-md-6">
					<div class="card-body">
						<h4 class="card-title">Year:</h4>
						<p class="card-text">@Model.Year</p>
						<h4 class="card-title">Color:</h4>
						<p class="card-text">@Model.Color</p>
						<h4 class="card-title">Category:</h4>
						<p class="card-text">@Model.CategoryName</p>
						<h4 class="card-title">Price per day:</h4>
						<p class="card-text">@Model.PricePerDay</p>
						<h4><a asp-action="Details" asp-controller="Engine" asp-route-id="@Model.EngineId" class="btn btn-primary">Engine Details</a></h4>
					</div>
				</div>
				<div class="col-md-6">
					<img src="@Model.ImageUrl" class="img-fluid" width="700" />
				</div>
			</div>
		</div>
	</div>
</body>
</html>

RentWheels/Views/Car/Edit.cshtml
@model CarFormViewModel

<h2>Edit Car</h2>

<partial name="_CarFormPartial" model="@Model"/>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

RentWheels/Views/Car/MyCars.cshtml
@model IEnumerable<MyCarsViewModel>

<partial name="_Notification" />

<table class="table">
	<thead>
		<tr>
			<th>Car</th>
			<th>Available:</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var car in Model)
		{
			<tr>
				<td>@($"{car.Brand} {car.CarModel}")</td>
				<td>
					@if (car.Available == "true")
					{
						<i class="fas fa-check text-success offset-2"></i>
					}
					else
					{
						<i class="fas fa-times text-danger offset-2"></i>
					}
				</td>
				<td><a asp-action="Edit" asp-controller="Car" asp-route-id="@car.Id" class="btn btn-primary">Edit</a></td>
				<td><a asp-action="Details" asp-controller="Car" asp-route-id="@car.Id" class="btn btn-secondary">Car Details</a></td>
				<td>
					<form asp-action="Remove" asp-controller="Car" asp-route-id="@car.Id" method="post">
						<button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to remove this car?');">Remove car</button>
					</form>
				</td>
			</tr>
		}
	</tbody>
</table>